name: Dimensions
main: me.xxastaspastaxx.dimensions.Dimensions
author: astaspasta
description: Allow players to easily build portals to another world
api-version: 1.13
version: 3.2.6
depend: [ProtocolLib]
softdepend: [BetterPortals, Vault, WorldEdit, WorldGuard, BentoBox, IridiumSkyblock, SuperiorSkyblock2, Oraxen, ItemsAdder, CustomItems, ModelEngine, LightAPI]
commands:
   dimensions:
      description: Main command
      usage: /<command>
      aliases: [dim]